services:

  mongo:
    image: bertreux/mongo:1.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: java1
      MONGO_INITDB_ROOT_PASSWORD: java1
    ports:
      - 27117:27017
    volumes:
      -  C:/docker-volumes/server-mongodb:/db/Data
  mongo-express:
    image: bertreux/mongo-express:1.0
    restart: always
    ports:
      - 8181:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: java1
      ME_CONFIG_MONGODB_ADMINPASSWORD: java1
      ME_CONFIG_MONGODB_SERVER: mongo